/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.osc.bikas.avro;
@org.apache.avro.specific.AvroGenerated
public enum Format implements org.apache.avro.generic.GenericEnumSymbol<Format> {
  REGISTRATION, FORGOT_PASSWORD  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Format\",\"namespace\":\"com.osc.bikas.avro\",\"symbols\":[\"REGISTRATION\",\"FORGOT_PASSWORD\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
