/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.osc.bikas.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OTPAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4537177423912429434L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OTPAvro\",\"namespace\":\"com.osc.bikas.avro\",\"fields\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"OTP\",\"type\":\"int\"},{\"name\":\"Attempts\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OTPAvro> ENCODER =
      new BinaryMessageEncoder<OTPAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OTPAvro> DECODER =
      new BinaryMessageDecoder<OTPAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OTPAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OTPAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OTPAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OTPAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OTPAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OTPAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OTPAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OTPAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence userId;
   private int OTP;
   private int Attempts;
   private java.lang.CharSequence name;
   private java.lang.CharSequence email;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OTPAvro() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param OTP The new value for OTP
   * @param Attempts The new value for Attempts
   * @param name The new value for name
   * @param email The new value for email
   */
  public OTPAvro(java.lang.CharSequence userId, java.lang.Integer OTP, java.lang.Integer Attempts, java.lang.CharSequence name, java.lang.CharSequence email) {
    this.userId = userId;
    this.OTP = OTP;
    this.Attempts = Attempts;
    this.name = name;
    this.email = email;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return OTP;
    case 2: return Attempts;
    case 3: return name;
    case 4: return email;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.CharSequence)value$; break;
    case 1: OTP = (java.lang.Integer)value$; break;
    case 2: Attempts = (java.lang.Integer)value$; break;
    case 3: name = (java.lang.CharSequence)value$; break;
    case 4: email = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'OTP' field.
   * @return The value of the 'OTP' field.
   */
  public int getOTP() {
    return OTP;
  }


  /**
   * Sets the value of the 'OTP' field.
   * @param value the value to set.
   */
  public void setOTP(int value) {
    this.OTP = value;
  }

  /**
   * Gets the value of the 'Attempts' field.
   * @return The value of the 'Attempts' field.
   */
  public int getAttempts() {
    return Attempts;
  }


  /**
   * Sets the value of the 'Attempts' field.
   * @param value the value to set.
   */
  public void setAttempts(int value) {
    this.Attempts = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Creates a new OTPAvro RecordBuilder.
   * @return A new OTPAvro RecordBuilder
   */
  public static com.osc.bikas.avro.OTPAvro.Builder newBuilder() {
    return new com.osc.bikas.avro.OTPAvro.Builder();
  }

  /**
   * Creates a new OTPAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OTPAvro RecordBuilder
   */
  public static com.osc.bikas.avro.OTPAvro.Builder newBuilder(com.osc.bikas.avro.OTPAvro.Builder other) {
    if (other == null) {
      return new com.osc.bikas.avro.OTPAvro.Builder();
    } else {
      return new com.osc.bikas.avro.OTPAvro.Builder(other);
    }
  }

  /**
   * Creates a new OTPAvro RecordBuilder by copying an existing OTPAvro instance.
   * @param other The existing instance to copy.
   * @return A new OTPAvro RecordBuilder
   */
  public static com.osc.bikas.avro.OTPAvro.Builder newBuilder(com.osc.bikas.avro.OTPAvro other) {
    if (other == null) {
      return new com.osc.bikas.avro.OTPAvro.Builder();
    } else {
      return new com.osc.bikas.avro.OTPAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for OTPAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OTPAvro>
    implements org.apache.avro.data.RecordBuilder<OTPAvro> {

    private java.lang.CharSequence userId;
    private int OTP;
    private int Attempts;
    private java.lang.CharSequence name;
    private java.lang.CharSequence email;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.osc.bikas.avro.OTPAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.OTP)) {
        this.OTP = data().deepCopy(fields()[1].schema(), other.OTP);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.Attempts)) {
        this.Attempts = data().deepCopy(fields()[2].schema(), other.Attempts);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.name)) {
        this.name = data().deepCopy(fields()[3].schema(), other.name);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.email)) {
        this.email = data().deepCopy(fields()[4].schema(), other.email);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing OTPAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.osc.bikas.avro.OTPAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.OTP)) {
        this.OTP = data().deepCopy(fields()[1].schema(), other.OTP);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Attempts)) {
        this.Attempts = data().deepCopy(fields()[2].schema(), other.Attempts);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.name)) {
        this.name = data().deepCopy(fields()[3].schema(), other.name);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.email)) {
        this.email = data().deepCopy(fields()[4].schema(), other.email);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.osc.bikas.avro.OTPAvro.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.osc.bikas.avro.OTPAvro.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'OTP' field.
      * @return The value.
      */
    public int getOTP() {
      return OTP;
    }


    /**
      * Sets the value of the 'OTP' field.
      * @param value The value of 'OTP'.
      * @return This builder.
      */
    public com.osc.bikas.avro.OTPAvro.Builder setOTP(int value) {
      validate(fields()[1], value);
      this.OTP = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'OTP' field has been set.
      * @return True if the 'OTP' field has been set, false otherwise.
      */
    public boolean hasOTP() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'OTP' field.
      * @return This builder.
      */
    public com.osc.bikas.avro.OTPAvro.Builder clearOTP() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Attempts' field.
      * @return The value.
      */
    public int getAttempts() {
      return Attempts;
    }


    /**
      * Sets the value of the 'Attempts' field.
      * @param value The value of 'Attempts'.
      * @return This builder.
      */
    public com.osc.bikas.avro.OTPAvro.Builder setAttempts(int value) {
      validate(fields()[2], value);
      this.Attempts = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Attempts' field has been set.
      * @return True if the 'Attempts' field has been set, false otherwise.
      */
    public boolean hasAttempts() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Attempts' field.
      * @return This builder.
      */
    public com.osc.bikas.avro.OTPAvro.Builder clearAttempts() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.osc.bikas.avro.OTPAvro.Builder setName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.name = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.osc.bikas.avro.OTPAvro.Builder clearName() {
      name = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.osc.bikas.avro.OTPAvro.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.email = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.osc.bikas.avro.OTPAvro.Builder clearEmail() {
      email = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OTPAvro build() {
      try {
        OTPAvro record = new OTPAvro();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.OTP = fieldSetFlags()[1] ? this.OTP : (java.lang.Integer) defaultValue(fields()[1]);
        record.Attempts = fieldSetFlags()[2] ? this.Attempts : (java.lang.Integer) defaultValue(fields()[2]);
        record.name = fieldSetFlags()[3] ? this.name : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.email = fieldSetFlags()[4] ? this.email : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OTPAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<OTPAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OTPAvro>
    READER$ = (org.apache.avro.io.DatumReader<OTPAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.userId);

    out.writeInt(this.OTP);

    out.writeInt(this.Attempts);

    out.writeString(this.name);

    out.writeString(this.email);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);

      this.OTP = in.readInt();

      this.Attempts = in.readInt();

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);
          break;

        case 1:
          this.OTP = in.readInt();
          break;

        case 2:
          this.Attempts = in.readInt();
          break;

        case 3:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 4:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










