grpc:
  server:
    port: 9100

spring:
  application:
    name: bikas-session-data-service
#database specific configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/osc
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true
#Kafka specific configuration
  kafka:
    bootstrap-servers: 192.168.99.223:19092
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://192.168.99.223:18081
