grpc:
  server:
    port: 9100

spring:
  application:
    name: bikas-session-data-service

  datasource:
    url: jdbc:postgresql://localhost:5432/osc
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      format_sql: true