grpc:
  server:
    port: 9090

spring:
  application:
    name: bikas-user-data-service

  datasource:
    url: jdbc:postgresql://localhost:5432/osc
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create