logging:
  level:
    org.springframework.web: DEBUG
#    io.grpc: DEBUG

grpc:
  client:
    GLOBAL:
      negotiation-type: PLAINTEXT
    user-data-service:
      address: static://localhost:9090
      negotiationType: PLAINTEXT

spring:
  kafka:
    bootstrap-servers: 192.168.99.223:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://192.168.99.223:18081