logging:
  level:
    io.grpc: DEBUG

grpc:
  client:
    GLOBAL:
      negotiation-type: PLAINTEXT
    user-data-service:
      address: static://localhost:9090
      negotiationType: PLAINTEXT

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8081